# Rome2rio

In [1]:
import urllib.request
import urllib.parse
import urllib.error
from bs4 import BeautifulSoup
import ssl
import json
import ast
import json
import os
from urllib.request import Request, urlopen
import pandas as pd
from bs4 import BeautifulSoup as bs
import requests
import re
from selenium import webdriver
from selenium.webdriver import Chrome
from selenium.webdriver.chrome.options import Options

In [2]:
chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
webdriver = "/home/sid2018-5/Téléchargements/chromedriver"

driver = Chrome(webdriver,chrome_options=chrome_options)

/home/sid2018-5/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: DeprecationWarning: use options instead of chrome_options
  import sys

In [3]:
def getdata(departure_city,arrival_city):
    
    url = "https://www.rome2rio.com/map/"+departure_city+"/"+arrival_city
    driver.get(url)

    items = len(driver.find_elements_by_class_name("route__title"))
    items2= len(driver.find_elements_by_class_name("route__details"))

    total=[]
    data=pd.DataFrame()
    for i in range(items):
        a=driver.find_elements_by_class_name("route__title")[i].text
        b=driver.find_elements_by_class_name("route__details")[i].text
        new = ((a,b))
        total.append(new)

    data = pd.DataFrame(total,columns=['itineraire','prix'])
    
    data['Data_Source'] = 'Rome2rio'
    data['Departure_city']=departure_city
    data['Arrival_city']=arrival_city
    data['Nb_bus_taken']=data.itineraire.str.count("Bus|bus")
    data['Nb_train_taken']=data.itineraire.str.count("Train|train")
    data['Nb_car_taken']=data.itineraire.str.count("Drive|drive|Rideshare|rideshare")
    data['Nb_plane_taken']=data.itineraire.str.count("Fly|fly")

    data['Price_max']=data['prix'].apply(lambda st: st[st.find("-")+1:])
    data['Price_max'] = data['Price_max'].str.replace('€', '')
    data['Price_min']=data['prix'].apply(lambda st: st[:st.find("-")])
    data['Price_min'] = data['Price_min'].str.replace('€', '')
    data['Duration1']=data['itineraire'].apply(lambda st: st[st.find("•")+1:])
    data['heure']=data['Duration1'].apply(lambda st: st[:st.find("h")])
    data['minute']=data['Duration1'].apply(lambda st: st[st.find("h")+1:st.find("m")])
    data['Duration']=data['heure'].astype(int)*60+data['minute'].astype(int)
    datafinal=data[['Data_Source','Departure_city', 'Arrival_city','Nb_bus_taken','Nb_train_taken','Nb_car_taken','Nb_plane_taken','Duration','Price_min','Price_max']]
    
    return datafinal

In [4]:
getdata("Paris","Barcelona")

,Data_Source,Departure_city,Arrival_city,Nb_bus_taken,Nb_train_taken,Nb_car_taken,Nb_plane_taken,Duration,Price_min,Price_max
0,Rome2rio,Paris,Barcelona,0,1,0,0,389,150,210
1,Rome2rio,Paris,Barcelona,1,0,0,0,910,28,65
2,Rome2rio,Paris,Barcelona,0,0,1,0,712,66,66
3,Rome2rio,Paris,Barcelona,0,0,1,0,575,120,180
4,Rome2rio,Paris,Barcelona,0,0,0,1,305,50,230
5,Rome2rio,Paris,Barcelona,0,0,0,1,295,47,213
6,Rome2rio,Paris,Barcelona,1,0,0,1,347,25,190
7,Rome2rio,Paris,Barcelona,0,1,0,1,385,92,455

In [5]:
example_capitale  = ["Paris","Berlin","Rome"]

In [6]:
tmp = [[x,y] for x in example_capitale for y in example_capitale if x!=y ]
appended_data = []
for i in range(len(tmp)):
    appended_data.append(getdata(tmp[i][0],tmp[i][1]))
appended_data = pd.concat(appended_data, ignore_index=True)

In [7]:
appended_data

,Data_Source,Departure_city,Arrival_city,Nb_bus_taken,Nb_train_taken,Nb_car_taken,Nb_plane_taken,Duration,Price_min,Price_max
0,Rome2rio,Paris,Berlin,0,0,0,1,285,47,174
1,Rome2rio,Paris,Berlin,0,0,0,1,281,89,387
2,Rome2rio,Paris,Berlin,0,0,0,1,293,97,246
3,Rome2rio,Paris,Berlin,0,0,0,1,438,49,159
4,Rome2rio,Paris,Berlin,0,1,0,1,339,117,338
5,Rome2rio,Paris,Berlin,0,1,0,0,509,187,277
6,Rome2rio,Paris,Berlin,0,1,0,0,743,90,140
7,Rome2rio,Paris,Berlin,1,0,0,0,855,45,65
8,Rome2rio,Paris,Berlin,1,0,0,0,989,37,45
9,Rome2rio,Paris,Berlin,0,0,1,0,576,120,190
10,Rome2rio,Paris,Rome,0,0,0,1,311,64,308
11,Rome2rio,Paris,Rome,0,0,0,1,325,67,325
12,Rome2rio,Paris,Rome,1,0,0,1,369,33,229
13,Rome2rio,Paris,Rome,0,1,0,1,385,83,387
14,Rome2rio,Paris,Rome,0,1,0,0,621,155,295
15,Rome2rio,Paris,Rome,1,0,0,0,1220,65,80
16,Rome2rio,Paris,Rome,0,2,0,0,844,118,236
17,Rome2rio,Paris,Rome,0,0,1,0,810,190,280
18,Rome2rio,Paris,Rome,0,1,1,0,1340,186,315
19,Rome2rio,Berlin,Paris,0,0,0,1,290,48,173
20,Rome2rio,Berlin,Paris,0,0,0,1,286,89,386
21,Rome2rio,Berlin,Paris,0,0,0,1,294,98,246
22,Rome2rio,Berlin,Paris,0,0,0,1,410,49,159
23,Rome2rio,Berlin,Paris,0,1,0,0,526,138,362
24,Rome2rio,Berlin,Paris,0,1,0,0,551,184,270
25,Rome2rio,Berlin,Paris,1,0,0,0,855,40,90
26,Rome2rio,Berlin,Paris,0,0,1,0,728,63,63
27,Rome2rio,Berlin,Paris,0,0,1,0,578,120,190
28,Rome2rio,Berlin,Rome,0,0,0,1,309,60,288
29,Rome2rio,Berlin,Rome,0,0,0,1,320,32,260
30,Rome2rio,Berlin,Rome,0,0,0,1,496,89,207
31,Rome2rio,Berlin,Rome,0,0,0,1,418,75,461
32,Rome2rio,Berlin,Rome,0,1,0,0,896,177,352
33,Rome2rio,Berlin,Rome,1,0,0,0,1545,50,148
34,Rome2rio,Berlin,Rome,1,0,0,0,1713,65,92
35,Rome2rio,Berlin,Rome,0,2,0,0,1077,192,266
36,Rome2rio,Berlin,Rome,0,0,1,0,826,200,300
37,Rome2rio,Berlin,Rome,0,1,1,0,957,263,364
38,Rome2rio,Rome,Paris,0,0,0,1,311,63,308
39,Rome2rio,Rome,Paris,0,0,0,1,325,67,325
40,Rome2rio,Rome,Paris,1,0,0,1,396,,
41,Rome2rio,Rome,Paris,0,1,0,1,385,57,291
42,Rome2rio,Rome,Paris,0,1,0,0,652,150,292
43,Rome2rio,Rome,Paris,1,0,0,0,1135,65,85
44,Rome2rio,Rome,Paris,0,2,0,0,877,119,239
45,Rome2rio,Rome,Paris,0,0,1,0,819,190,280
46,Rome2rio,Rome,Paris,0,1,1,0,1319,188,313
47,Rome2rio,Rome,Berlin,0,0,0,1,309,59,289
48,Rome2rio,Rome,Berlin,0,0,0,1,322,31,259
49,Rome2rio,Rome,Berlin,0,0,0,1,412,74,461
50,Rome2rio,Rome,Berlin,0,1,0,1,379,78,312
51,Rome2rio,Rome,Berlin,0,1,0,1,381,53,334
52,Rome2rio,Rome,Berlin,0,1,0,0,912,174,314
53,Rome2rio,Rome,Berlin,1,0,0,0,1496,60,74
54,Rome2rio,Rome,Berlin,1,0,0,0,1558,72,97
55,Rome2rio,Rome,Berlin,0,2,0,0,1072,310,600
56,Rome2rio,Rome,Berlin,0,1,1,0,1195,203,278
57,Rome2rio,Rome,Berlin,0,0,1,0,829,200,300

In [8]:
col_names = ['Date_Review','Review','Airline_Name','Airline_Type','Region_Operation','Aircraft_Type','Cabin_Class','Type_Of_Lounge',
               'Type_Of_Traveller','Date_Visit','Date_Flown','Airport','Route','Category','Category_Detail',
               'Cabin_Staff_Service','Lounge_Staff_Service','Bar_And_Beverages','Food_And_Beverages','Ground_Service','Catering','Cleanliness',
              'Lounge_Comfort','Aisle_Space','Wifi_And_Connectivity','Inflight_Entertainment','Viewing_Tv_Screen','Power_Supply',
              'Seat','Seat_type','Seat_Comfort','Seat_Legroom','Seat_Storage','Seat_Width','Seat_Recline','Washrooms',
               'Value_For_Money','Overall_Customer_Rating','Overall_Service_Rating','Overall_Airline_Rating',
              'Recommended','Title','Author','Description','Date_publication',
           'View_count','Likes','Dislikes','Nb_subscribers','Nb_comments','Nb_sharing','Hashtags','Awards','Registration','Language']

In [9]:
datafinal=pd.DataFrame(columns=col_names)

In [10]:
pd.concat([appended_data,datafinal])

/home/sid2018-5/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

,Aircraft_Type,Airline_Name,Airline_Type,Airport,Aisle_Space,Arrival_city,Author,Awards,Bar_And_Beverages,Cabin_Class,...,Seat_Width,Seat_type,Title,Type_Of_Lounge,Type_Of_Traveller,Value_For_Money,View_count,Viewing_Tv_Screen,Washrooms,Wifi_And_Connectivity
0,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,Rome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,Paris,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,Berlin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
rom2rio_=pd.concat([appended_data,datafinal],sort=False)

liste_capitale  = ["Paris","Berlin","Rome","Madrid","London","Dublin","Lisbon",
"Brussels","Luxembourg","Amsterdam","Bern","Copenhagen","Oslo","Stockholm","Helsinki",
"Tallinn","Riga","Vilnius","Warsaw","Prague","Vienna","Bratislava","Budapest","Ljubljana","Ankara"
"Bucharest","Belgrade","Sofia","Tijana","Skopje","Athens","Chisinau","Kiev","Minsk","Moscow",
"Tbilissi","Bakou","Verevan","Sarajevo","Reykjavik","Valletta","Zagreb","Nicosia","Andorra la Vella",
"San Marino","Vatican City"]

In [12]:
rom2rio = rom2rio_.to_json()
with open('data_rom2rio.json', 'a', encoding='utf8') as outfile:
        json.dump(rom2rio, outfile, ensure_ascii=False,indent=4)